.TH "LaunchPadExport.php" 3 "Tue Nov 29 2011" "Version 2.0" "LaunchPad Export for Mantis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LaunchPadExport.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBLaunchPadExportPlugin\fP"
.br
.RI "\fIImplements a Mantis plugin. Only custom functions are defined, see Mantis documentation for the rest. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LaunchPad Export for Mantis from the source code.
