.TH "todo" 3 "Tue Nov 29 2011" "Version 2.0" "LaunchPad Export for Mantis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBGlobal \fB$pageWeWantToSee\fP \fP" 1c
I'm not sure if Mantis allows moving/configuring the upload folder, if so, this hardcoding of ./uploads/ should be fixed. 
.PP

